### ISSUE TITLE
Titel korrigieren

### ISSUE THREAD

**Issue by 205er** [ffbsee/praesentation#2]
Den Titel des Repository wie folgt abändern:

"Was ist dieses Freifunk eigendlich?" ==> "Was ist dieses Freifunk eigentlich?"

**Comment by DO1JLR** [comment]
Erledigt:
https://github.com/ffbsee/praesentation/commit/e9191b18869ec056bff1f08f55cd04d726582baf
https://github.com/ffbsee/praesentation/commit/09ee2ec9ae8e18acf4c5ce840d5bf00d192af5d1
